version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - "APP_ENV=local"
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: stockdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
